# Generated by Django 2.0.8 on 2018-08-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='members',
            field=models.ManyToManyField(through='Listing.ClassList', to='Listing.Student'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Listing.Section'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Listing.Student'),
        ),
    ]
